# Generated by Django 5.0.8 on 2025-02-11 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("healthcare", models.CharField(max_length=167, null=True)),
                ("amenity", models.CharField(max_length=80, null=True)),
                ("operatorty", models.CharField(max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["geom"], name="geom_index")],
            },
        ),
    ]
