# Generated by Django 5.0.8 on 2025-02-10 11:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilities",
            name="amenity",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilities",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="healthfacilities",
            name="healthcare",
            field=models.CharField(max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilities",
            name="name",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilities",
            name="operatorty",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name="healthfacilities",
            index=models.Index(fields=["geom"], name="geom_index"),
        ),
    ]
